// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBdrbg0GAQ0DuRUHypw5Dpm46UvdVsFJY',
    appId: '1:939199094656:android:c93019d816484ce4e76b65',
    messagingSenderId: '939199094656',
    projectId: 'su24-sep490-koreandictionary',
    databaseURL: 'https://su24-sep490-koreandictionary-default-rtdb.firebaseio.com',
    storageBucket: 'su24-sep490-koreandictionary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa4ngsJ7uyca_bIvanoSn06QIsad5zZjU',
    appId: '1:939199094656:ios:bd0d7e900a0f9e78e76b65',
    messagingSenderId: '939199094656',
    projectId: 'su24-sep490-koreandictionary',
    databaseURL: 'https://su24-sep490-koreandictionary-default-rtdb.firebaseio.com',
    storageBucket: 'su24-sep490-koreandictionary.appspot.com',
    iosBundleId: 'com.example.myapp',
  );
}
